# Generated by Django 4.2.19 on 2025-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatars/', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
